clusterLocation: ENC[AES256_GCM,data:r3Cf++ikKrg=,iv:8ap7LCTe8JoeacHOCbgB2tgUNPTHe2paX99b4bPkm74=,tag:cqVqvBGyfd1HNeW3Zl+37Q==,type:str]
clusterName: ENC[AES256_GCM,data:BYHD0sTrej3tMg==,iv:ou5yaLAlwK7DOj1U6eyX9BQouJrEyZ2PXNTn7zVwl5s=,tag:7W8Y+OvoR0IBXQiPmJ8pJA==,type:str]
serviceAccountName: ENC[AES256_GCM,data:xZg4e1g=,iv:ccU/EyxnI6pnpLemBWsS2ENltCI/bEhg5gcd6xHJ4nc=,tag:GzuOUiZRr7pHnQgWBImEyg==,type:str]
namespace: ENC[AES256_GCM,data:s3CWlED1,iv:6gVWJNMOI4Zr5KEqS0q9QrwyxGfohVX4zxxj9aCTg5o=,tag:eaTwTVxjLsQjR24YjETmWw==,type:str]
namespace_es: ENC[AES256_GCM,data:ZkRcJr2U8p8NHh2AfOtdMw==,iv:WJDAGVKuQ5CnPso+hLIGh886nrmNlpl8OptMAFHRQbE=,tag:ZUz10W0q4VXFXyjCRH5wLg==,type:str]
project_id: ENC[AES256_GCM,data:vVrawXo046Btfz8m,iv:I8NRkEIVn/lBlEXJyw73tyHk/A0wnpM9c6coRxoKDaE=,tag:3NW/Nr3LyiHWPeCdsZy3bQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/csye7125-prd/locations/global/keyRings/sops-key/cryptoKeys/sops-key
          created_at: "2025-04-11T10:07:00Z"
          enc: CiQAly6Hlk54J05Puc0Bac5MEwdsf82OC/wNITWW0CPzc5rRfyISSQCbzmwTh7yaiWA9lGDSPqvfSylAabh4poPqPHE+uqfffGCIr+3rcHtdDSKoUmMnV8dQuFNnwIhgeYIUsBc+Lvdh7kIERaoAsdQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-11T10:07:00Z"
    mac: ENC[AES256_GCM,data:nlY3wNbcsDKEGUnOiZafdUpNAXaI7hFQgGoNvdFcAOc0adOE9xfHGeQADTa1qtae+JkZcX9vLMcGG0NIZQGKzHC6qsrjIvNoz2rCfIwYsvQ4BRWgDWGvY63fzyC/ZtUzvYypqkw82EmMXqOo6QPTAHki4LX5pEnjn3nVRgVL1bk=,iv:N5qg+UWFOaw8v7YgUjHzSNcZJ1ISY2vdWZhXbgLCeb8=,tag:Dm0EtBWvouF/tMH32xOY8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
