clusterLocation: ENC[AES256_GCM,data:5o9BuqcA20Q=,iv:xTQ9qfdFgj0q8mgIyphur/xot8w/wHXQUeULMUzUGls=,tag:fs2IBCeNAmv//ACDKovrwQ==,type:str]
clusterName: ENC[AES256_GCM,data:xMM6/SwoBp6+6A==,iv:6cjcX9+mD0c4f2Nf9iYYU5nWOY5y+/s9UhwN0uGKxfM=,tag:vMdGIdAb+uxh1jfnXeI95g==,type:str]
serviceAccountName: ENC[AES256_GCM,data:kQQqSE8=,iv:f945cgEoMkzqtr121hmxBLF1ojUhUKbNcHApynqR0N4=,tag:HAHq8uoCFe5PiyHMZZVUig==,type:str]
namespace: ENC[AES256_GCM,data:fY0z5mbJ,iv:jXDU0ImsxjF5QSqcm9jZKAJ/wzijWZbQK4JG3QZ5NqM=,tag:f6z3LZupzTrSJvctYNiVhA==,type:str]
project_id: ENC[AES256_GCM,data:bJBAiEQlW2NqDzOI,iv:Al0bi7LlUIlno4RytV1/C6kPz/n+i4MJeWePLC/apL0=,tag:wFLhupMnMldQGQTBSV0B8w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/csye7125-prd/locations/global/keyRings/sops-key/cryptoKeys/sops-key
          created_at: "2025-03-14T20:17:30Z"
          enc: CiQAly6HlhB9od5tVvS7LSK2bIDQ4f0YQoZmR0ZqtMfzHAtwk4gSSQCbzmwTtF4MUpVMukGB863Up1i2a83qXtcnUp0pFIIjwkLZD/JKg5U69a2Uf4YlFRIVUZZr8c4Jha630O/tcARez+aOkIzEbfQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-14T20:17:31Z"
    mac: ENC[AES256_GCM,data:nqX26/uQDMqe4cX1lgykwx3iZia7Pn/UkYCWOClOuvdvcWykNLI5Vh3dy1yFdWFTIEf7ZZCSYoKw72kInnazn70hzei6/B70yN/QZc2OF7ChULQzv4XgcJ0zv8f0nWII0ng7KoJvOc74OYqTurayRJRA6YZtatUutZ8G0dPCEGk=,iv:H1RF9d63uZ3XC+CSkIqS+zNyCcA5vbNcCIgV65EGGlQ=,tag:ZsPpcBjA1mT9leHQnONiOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
