namespace: ENC[AES256_GCM,data:ujeZQxvf,iv:T31RhefyZvWYULDCKQDv1PLd8gQveTrH43wX1bUWpPg=,tag:EY4aiKKWbcwkHWJQGBe+5g==,type:str]
project_id: ENC[AES256_GCM,data:u1WvKHODJOl+dSOk,iv:02MpdiaCihGa8CGeBaYKU97ohm56e68Ybra+SUKImqI=,tag:0Hlv9IiqyjXVdwU3AHB+7Q==,type:str]
certmanagertype: ENC[AES256_GCM,data:G2j909X+zVZ9pMBc70fS0IJlHg==,iv:fL51diUQNcG+KX3C9YWP/g5C/jCd6YGB+omc9Y1kqrU=,tag:x98Csg2EVxh0PfqBM9GHCw==,type:str]
staticipname: ENC[AES256_GCM,data:lN1iE2u/9ijxr2Ibey7f3A==,iv:YnTwa+RdQQfF7Q/IuyMLpfBX8k5Yk58wL5Zkxzs3YKs=,tag:jSgyxHNc0TiX4gHir1tkpw==,type:str]
hostname: ENC[AES256_GCM,data:YcblURa94vk8HFmHt80mDaiAmDDKiJViIyh2dJE=,iv:kRibotJqoI3vSLr5VbpL/tOXZyJY4vl68v+2P05gZ/A=,tag:/5ryEjKZiAHeDjnNUPchsw==,type:str]
GCS_BUCKET_NAME: ENC[AES256_GCM,data:Lwsci0ItuDA7wuy9OofqpITEt8FmGw==,iv:pUgbtiLIXqhmix2gMR/iArqIkQrE8vYP1ZBeUPrO5aE=,tag:h+xGLgRbRXZVK/pbMnyzSg==,type:str]
postgres:
    user: ENC[AES256_GCM,data:x6SWbhOLkgE=,iv:pulVip0ZRHf/KGIpbMddc7PVPLFnW5m16zXMgou2Rss=,tag:YTmNJ2b9Je26wwWm7F/IUw==,type:str]
    db: ENC[AES256_GCM,data:Hc52,iv:KVNqbR2SKNG3wssCt5CIxkASUWHE3NURQsREWix1alo=,tag:Pj2RExjcbB/ob4J9qJsvNg==,type:str]
    storage: ENC[AES256_GCM,data:vzzU,iv:yErRE7vqx049SJwLKJb+T/JRZ4AKNttRyqxiKTN7Brg=,tag:OoyxX9UX6MeWxPRtirwhdg==,type:str]
    image: ENC[AES256_GCM,data:NulmJLrSp1BWVaxpVELJ,iv:RJjdgi34AwXWYksXEqSR/ehFmZJhkvZAGbhUiaxpci0=,tag:hMfddMmmZdX+UrDzL1yb7Q==,type:str]
    replicas: ENC[AES256_GCM,data:Jg==,iv:ZhIjFsXvyUskavOmiWZt3BkysCYQoNMWUXA/U7r41xU=,tag:QiY9NY7QCyPHn+OvoFKLZA==,type:int]
dockerhubSecret:
    auths:
        https://index.docker.io/v1/:
            username: ENC[AES256_GCM,data:hpIFtmkyUX4X,iv:y3QfWaQvdmRCxLtt1uvFMiA/DPXDCTF/tnX5S5ttlsY=,tag:JoiVk1fL7Rj1EW+7RKX4xw==,type:str]
            password: ENC[AES256_GCM,data:8oZCX9I4+CQb6tC07vqgCFnclLm4Pz7mIt5oNf/Vb9mxMNGl,iv:im9zNehWeUC7ZXazbMZeGAtZ2XgRye7eOxph4JxmXh0=,tag:lp4ZJQLpTHd9v/jLJMMouw==,type:str]
goApp:
    image: ENC[AES256_GCM,data:90a9msDZQrQAiRJu8b7VCsFC32N5mgi20lM=,iv:/IxgGgPEeNHIDTkHR+6xvuouQQC2XjNS/QCXNs1mNq8=,tag:iLGGp53/sufp1A973xLZNA==,type:str]
    initImage: ENC[AES256_GCM,data:uyU5PbuDRegsCzfGtyYu0Urqkii5ZQ==,iv:jRXD+p0OeIstMw315ygy/wS1bQEySTjVsVkB9gFQ5/o=,tag:tbzFXMWufLAsSYKGeuTSTg==,type:str]
    replicaCount: ENC[AES256_GCM,data:5A==,iv:PbW7vn43hbcUN7vNFWIeCa+BljZBYBYkRIATiCP55IE=,tag:me1/l0phZtPmc5P+3edlWw==,type:int]
    servicePort: ENC[AES256_GCM,data:hXM=,iv:fKVVrGwhb2AhD/0dNnLL/tITVPnMBSe405hFX/uSUhY=,tag:K0TevqSKygfnSIgsAV3n+g==,type:int]
    targetPort: ENC[AES256_GCM,data:9hg4cA==,iv:jvP6VWHS/ZX4WvRQGd2s1OwpIBLeeqsVu3L6fXuQDWU=,tag:gRz6h2kD/K6BkRb37iGn4A==,type:int]
    nodePort: ENC[AES256_GCM,data:s39NVUY=,iv:eGRgIxF7mBXtS6Wfohbb7yaYF5hH509+ZjOO9LtBeG8=,tag:XP7GA9S0S+iuFlKbd79lMA==,type:int]
    secret:
        DB_HOST: ENC[AES256_GCM,data:7xCZSaf4tts=,iv:/fIqFAa20zMwVdIboY5vabZK2qg1huDKzmOqF0Ywb80=,tag:mZk/N/J2mTrFgHjXadU+6Q==,type:str]
        DB_PORT: ENC[AES256_GCM,data:9Vv4mw==,iv:9uN6TSrYilqInnKa0eFGUNMtFQ7FMWfnWbdM4Xwoi6U=,tag:+hsbemynCghyfytjlZEo1A==,type:str]
        DB_USER: ENC[AES256_GCM,data:fZuK/2KjD54=,iv:6QaOfpOJDMumG2eNbIHTPFqjQxbyPDydZx3HZzlSvx0=,tag:RrJOGllZ7LL80zi1Okxbww==,type:str]
        DB_NAME: ENC[AES256_GCM,data:BuyK,iv:sGHbN6MFCi1JFfs8V6FGPV4v1erBxo3GH7V1tDkpKag=,tag:bHccvL0kfhathf149E4E4g==,type:str]
networkPolicy:
    enabled: ENC[AES256_GCM,data:BhA4Kg==,iv:5d3OCVjFfs8cmPGKr9CaIRWqePdztdSZ/joPbVrdIF0=,tag:dY5RmKdETU4sDsTIwFtzKA==,type:bool]
    name: ENC[AES256_GCM,data:8ID2ysUjcPT8C6S5YbDVKgxoQiqQReTbCY03,iv:1IO8uNzbAZAJ9Qac79Tt3xq6D8QBrc24vtEIEAXJMPw=,tag:povjCCYZiliDT8hhudB6Fw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/csye7125-prd/locations/global/keyRings/sops-key/cryptoKeys/sops-key
          created_at: "2025-03-28T10:55:40Z"
          enc: CiQAly6Hlm4JdTasxGXS8T5bdgTOiMuvTsXghe4fWcPhrMSCjoQSSQCbzmwTuL7jL6Kp4YLL7vjkfSRzNpjDx4m8Kqmksf0VAUN6SmNUWLOodHWaTQm4faZwJvW32VFKJp5SVy8/dpYgH8ToFuYgCZQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-28T10:55:40Z"
    mac: ENC[AES256_GCM,data:XiIXXkjizbHXi4E8K7EVLF1kXhTWS7GmAFpZaudFDhH5EU3NWEmN2cCytGd1yKwRVCwtV0j+1ehr2K47raJ63+qWe7vIwSCxMNtYXulgxAuEq5ykGnpMzL2qiLPRT7Ptbp2dFbI3YRnSIkPq9YGbn8Na5nSgOoN6G6wJTtPFKOg=,iv:4PTA37bVWJpUk4rpoUZsPlW+OG6kVVnptdiKtp705d4=,tag:0Ir+S7htagWBKiTkUXFOIw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
