letsencryptserver: ENC[AES256_GCM,data:BC2Z4qhf9fPTrmODqp31IjfRLmptPFbYgfqK1aDMW7i6uBKg6aPo2Q4TAl3KDWQK8JnbdkKI,iv:mz3a0Rh/4Y0uPhm7Kshu1S2tVTTK8Ml1xTRlSUx5PEM=,tag:KDcVK6ySjADMrk+PbBGlwQ==,type:str]
letsencryptemail: ENC[AES256_GCM,data:dLdRtNYjxaTTr4eql7gi47+PL4Dog1Bv8Qm2Dg==,iv:W/Og6DenBz5066gxN3xUPbEmbEE76oXZLAUzh+sQysg=,tag:q4BC85jkRWcG/gcse6pX4A==,type:str]
namespace: ENC[AES256_GCM,data:6uaN5+4cz3srQ8+l,iv:IOTUkbw3uzahLzf9N2ExFB5MYQGRm7xyZaDdGL4MkKY=,tag:FkbpKYVbpGc1y49vi0Xv9w==,type:str]
certmanagertype: ENC[AES256_GCM,data:ulZVzx9/S9mvCJvtEWSIu7N79Q==,iv:KAvnSOsX8qKdmfKWZgcejOKklWM8kIljoA9vfTim0dw=,tag:CCmTDbA5diGJALziAq1Kwg==,type:str]
hostname: ENC[AES256_GCM,data:GhsWeWl/BZs4rpFRuixP8GMG4YiXlS5bcjuBEYI=,iv:b4fG3pjwydMABRpVDnFbRISkv7QyYACiot2OwTWHCRY=,tag:HZ7cwg0IlDTIrAFzyRE0bg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/csye7125-prd/locations/global/keyRings/sops-key/cryptoKeys/sops-key
          created_at: "2025-03-28T10:55:49Z"
          enc: CiQAly6HltVGNp54VTVXFtN1/AkWZDVKiyM7j6Xptat/JxCSveASSQCbzmwTo2RFm3GH8bk+4YuGoKPi5Vsq5xUwRDGTSBr6Dke4Uv7NfNLRdOmWLDJbFXbfqBJrfH92IoVmmmUFKG3DsXFGMIGZ53E=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-28T10:55:49Z"
    mac: ENC[AES256_GCM,data:s4clGZ7x4HX8hsEu7kO9IBqajfEKSoEgapipAjVR5Hpsgtt8dO9RKLxgiTt132SURN8JF1qTZkQWbKZexYdqCpkbTydZGRPQsr+0jhybxDkd3fFx6GN53QmVEGmMYr+rX5eo9WuoWO426gVSASgpwYxv7vQzwGxFV+EGD/h8beQ=,iv:+12Dp924UDKRquqLMeEvsUfhV57MDwj/kTL7wqvK6j4=,tag:PIRMHeg8EmyJuEpdwWu5iA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
